[project]
name = 'github_classroom_toolkit'
readme = 'README.md'
classifiers = [
    'Development Status :: 1 - Planning',
    'License :: OSI Approved :: GNU Affero General Public License v3',
    'Topic :: Software Development :: Build Tools',
    'Programming Language :: Python :: 3',
    'Programming Language :: Java',
    'Programming Language :: Kotlin',
]
requires-python = '>=3.8'
dependencies = [
    'pandas',
]
dynamic = ['description', 'version', 'authors', 'maintainers']

[project.urls]
Repository = 'https://github.com/FynnFreyer/GradingToolkit'
Issues = 'https://github.com/FynnFreyer/GradingToolkit/issues'

[project.scripts]
autograde = 'github_classroom_toolkit.__main__:main'

[project.optional-dependencies]
dev = [
    'autopep8',
    'coverage[toml]',
    'isort',
    'mypy',
    'myst-parser',
    'pytest',
    'pytest-cov',
    'ruff',
    'sphinx',
    'sphinxcontrib-mermaid',
    'sphinxcontrib-plantuml',
    'sphinxcontrib-relativeinclude',
    'uv',
]

[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[tool.hatch]
description = { path = 'src/github_classroom_toolkit/__about__.py' }
version = { path = 'src/github_classroom_toolkit/__about__.py' }
authors = { path = 'src/github_classroom_toolkit/__about__.py' }
maintainers = { path = 'src/github_classroom_toolkit/__about__.py' }

# Formatting options
[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true

[tool.isort]
src_paths = ['src', 'tst']
line_length = 120

# Testing options
[tool.pytest.ini_options]
pythonpath = 'src/'
testpaths = 'tst/'
markers = [
    'model: tests regarding the model package',
    'e2e: end to end tests that require an authenticated github connection',
]

[tool.coverage.run]
branch = true
relative_files = true
omit = ['tst/*']

[tool.coverage.report]
fail_under = 75
skip_covered = true
exclude_lines = [
    'if __name__ == .__main__.:',
]

# Linting options
[tool.ruff]
line-length = 120
format = 'pylint'
src = ['src', 'tst']
select = ['E', 'F', 'B', 'Q']
show-fixes = true

[tool.ruff.mccabe]
max-complexity = 10
